---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: 'Build & Deploy - Alpha'
on:
  push:
    branches:
      - alpha

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

###############
# Set the Job #
###############
jobs:

  # Deploy to NPM
  deploy_to_npm:
    name: Deploy to NPM (beta)
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: alpha
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: rubenhalman
      - run: npm ci
      - run: |
          git config --global user.name nvuillam
          git config --global user.email nicolas.vuillamy@gmail.com
      - run: ALPHAID=$(date '+%Y%m%d%H%M') && npm version prerelease --preid="alpha$ALPHAID"
        shell: bash
      - run: npm publish --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
