---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - RELEASE"
on:
  release:
    # Want to run the automation when a release is created
    types: ["created"]

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

###############
# Set the Job #
###############
jobs:
  deploy_to_npm:
    name: Deploy to NPM (release)
    runs-on: ubuntu-latest
    permissions: read-all
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          scope: rubenhalman
      - name: Publish
        run: |
          npm install
          npm run build
          cp package.json out
          cp tsconfig.cjs.json out
          cd out
          npm pack
          npm publish $(ls -all | grep "lightningflowscanner" | awk '{print $9}')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKENX }}
