name: Test

on: [pull_request]

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm ci
      - name: Run test UMD compile
        run: npm run vite:dist
      - name: Run test package compile
        run: npm run swc:sim:pack
      - name: Run unit tests
        run: npm run test
